module.exports = {
  fetching: 'Error fetching',
  save: 'Error saving',
  update: 'Error updating',
  deleting: 'Error deleting',
  dismiss: 'Error dismiss',
  Internal: 'Internal server error',
  access: 'Unauthorized access',
  download: 'Error downloading file:',
  found: 'not found',
  connect: 'Connection error',
  authentication: 'User verification error:',
  deserialize: 'Error when deserializing user:',
  session: 'Error while setting up session:',
  exit: 'Error when exiting:',
}
